nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:5173', 'http://127.0.0.1:8000']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
        hosts: []
    paths:
        '^/':
            allow_origin: ['http://localhost:5173', 'http://127.0.0.1:8000']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Link']
            max_age: 3600
